import { AgentContext } from '../../models/agent-capability.model';

export const databaseContext: AgentContext = {
  currentWorkspace: '/Users/danielmc/Desktop/CodeIA/Sesion 8/projectops-dashboard',
  availableServices: [
    'JsonDatabaseService',
    'ProjectService',
    'TaskService',
    'TeamService',
    'MetricsService'
  ],
  environmentVariables: {
    DATABASE_TYPE: 'JSON',
    STORAGE_TYPE: 'localStorage',
    DATABASE_FILE: 'assets/database.json',
    STORAGE_KEY: 'projectops_database',
    MAX_RECORDS_PER_ENTITY: '10000',
    BACKUP_ENABLED: 'true',
    BACKUP_INTERVAL_HOURS: '24'
  },
  knowledgeBase: [
    {
      topic: 'JSON Database Schema',
      content: `The database follows a simple JSON structure with collections:
        - projects: Project management data
        - tasks: Task tracking data
        - teamMembers: Team member information
        - agents: AI agent configurations
        - agentTasks: Tasks assigned to agents
        - agentLogs: Agent activity logs`,
      source: 'database.json',
      relevance: 1.0,
      lastUpdated: new Date()
    },
    {
      topic: 'Data Relationships',
      content: `Key relationships:
        - Projects have teamMemberIds[] (many-to-many)
        - Tasks have projectId (many-to-one) and assignedToId (many-to-one)
        - AgentTasks have assignedTo (agent ID, many-to-one)
        All relationships are managed via IDs (string type)`,
      source: 'schema-documentation',
      relevance: 0.95,
      lastUpdated: new Date()
    },
    {
      topic: 'ID Generation',
      content: `IDs are generated sequentially as strings:
        - Format: "1", "2", "3", etc.
        - Generated by JsonDatabaseService.generateId()
        - Unique per entity type
        - Never reused after deletion`,
      source: 'JsonDatabaseService',
      relevance: 0.9,
      lastUpdated: new Date()
    },
    {
      topic: 'Date Handling',
      content: `Dates are stored as ISO 8601 strings in JSON.
        JsonDatabaseService automatically converts:
        - String dates to Date objects on load
        - Date objects to ISO strings on save
        Fields with Date type: createdAt, updatedAt, startDate, endDate, dueDate, joinedDate`,
      source: 'JsonDatabaseService',
      relevance: 0.85,
      lastUpdated: new Date()
    },
    {
      topic: 'Persistence Strategy',
      content: `Two-tier persistence:
        1. Primary: localStorage (key: 'projectops_database')
        2. Fallback: HTTP load from assets/database.json
        Changes are immediately saved to localStorage.
        No server-side persistence in current implementation.`,
      source: 'JsonDatabaseService',
      relevance: 0.9,
      lastUpdated: new Date()
    },
    {
      topic: 'Validation Rules',
      content: `Required fields per entity:
        - Project: id, name, description, status, startDate, progress, createdAt, updatedAt
        - Task: id, projectId, title, description, status, priority, tags, createdAt, updatedAt
        - TeamMember: id, name, email, role, availability, isActive, joinedDate
        - Agent: id, type, name, description, status, skills, tools, context, constraints
        Enums must match defined values (e.g., ProjectStatus, TaskStatus, AgentType)`,
      source: 'models',
      relevance: 1.0,
      lastUpdated: new Date()
    },
    {
      topic: 'Transaction Semantics',
      content: `No true transactions available.
        Best practices:
        - Create backup before complex operations
        - Validate all data before writes
        - Use rollback procedures on errors
        - Log all operations for audit trail`,
      source: 'best-practices',
      relevance: 0.8,
      lastUpdated: new Date()
    }
  ],
  configuration: {
    maxRetries: 3,
    retryDelayMs: 1000,
    batchSize: 100,
    enableValidation: true,
    autoBackup: true,
    strictMode: true,
    cacheEnabled: false
  }
};
