import { Project } from '../models/project.model';
import { Task, TaskPriority } from '../models/task.model';
import { TeamMember } from '../models/team-member.model';
import { ProjectStatus, TaskStatus } from '../models/status.model';
import { MemberRole } from '../models/team-member.model';

export const MOCK_PROJECTS: Project[] = [
  {
    id: '1',
    name: 'E-Commerce Platform Redesign',
    description:
      'Complete redesign of the e-commerce platform with modern UI/UX',
    status: ProjectStatus.IN_PROGRESS,
    startDate: new Date('2024-10-01'),
    endDate: new Date('2025-03-31'),
    budget: 150000,
    progress: 65,
    teamMemberIds: ['1', '2', '3', '4'],
    createdAt: new Date('2024-10-01'),
    updatedAt: new Date('2024-12-11'),
  },
  {
    id: '2',
    name: 'Mobile App Development',
    description: 'Native iOS and Android application for customer engagement',
    status: ProjectStatus.IN_PROGRESS,
    startDate: new Date('2024-11-15'),
    endDate: new Date('2025-06-30'),
    budget: 200000,
    progress: 40,
    teamMemberIds: ['2', '5', '6'],
    createdAt: new Date('2024-11-15'),
    updatedAt: new Date('2024-12-11'),
  },
  {
    id: '3',
    name: 'API Infrastructure Upgrade',
    description: 'Upgrade backend infrastructure and API endpoints',
    status: ProjectStatus.PLANNING,
    startDate: new Date('2025-01-01'),
    endDate: new Date('2025-04-30'),
    budget: 80000,
    progress: 10,
    teamMemberIds: ['3', '7'],
    createdAt: new Date('2024-12-01'),
    updatedAt: new Date('2024-12-11'),
  },
  {
    id: '4',
    name: 'Data Analytics Platform',
    description: 'Build comprehensive analytics dashboard and reporting tools',
    status: ProjectStatus.COMPLETED,
    startDate: new Date('2024-08-01'),
    endDate: new Date('2024-11-30'),
    budget: 120000,
    progress: 100,
    teamMemberIds: ['1', '4', '8'],
    createdAt: new Date('2024-08-01'),
    updatedAt: new Date('2024-11-30'),
  },
];

export const MOCK_TASKS: Task[] = [
  {
    id: '1',
    projectId: '1',
    title: 'Design homepage mockups',
    description: 'Create high-fidelity mockups for the new homepage',
    status: TaskStatus.DONE,
    assignedToId: '1',
    dueDate: new Date('2024-11-15'),
    priority: TaskPriority.HIGH,
    estimatedHours: 16,
    actualHours: 18,
    tags: ['design', 'ui'],
    createdAt: new Date('2024-10-05'),
    updatedAt: new Date('2024-11-15'),
  },
  {
    id: '2',
    projectId: '1',
    title: 'Implement checkout flow',
    description: 'Develop and test the new checkout process',
    status: TaskStatus.IN_PROGRESS,
    assignedToId: '2',
    dueDate: new Date('2024-12-20'),
    priority: TaskPriority.CRITICAL,
    estimatedHours: 32,
    actualHours: 24,
    tags: ['development', 'backend'],
    createdAt: new Date('2024-10-10'),
    updatedAt: new Date('2024-12-11'),
  },
  {
    id: '3',
    projectId: '2',
    title: 'Setup CI/CD pipeline',
    description: 'Configure GitHub Actions for automated deployments',
    status: TaskStatus.TODO,
    assignedToId: '5',
    dueDate: new Date('2025-01-10'),
    priority: TaskPriority.HIGH,
    estimatedHours: 8,
    tags: ['devops', 'infrastructure'],
    createdAt: new Date('2024-11-20'),
    updatedAt: new Date('2024-12-11'),
  },
];

export const MOCK_TEAM_MEMBERS: TeamMember[] = [
  {
    id: '1',
    name: 'Alice Johnson',
    email: 'alice@example.com',
    role: MemberRole.PROJECT_MANAGER,
    avatar: 'https://ui-avatars.com/api/?name=Alice+Johnson',
    projectIds: ['1', '4'],
    skills: ['Project Management', 'Leadership'],
    availability: 100,
    isActive: true,
    joinedDate: new Date('2024-01-15'),
  },
  {
    id: '2',
    name: 'Bob Smith',
    email: 'bob@example.com',
    role: MemberRole.DEVELOPER,
    avatar: 'https://ui-avatars.com/api/?name=Bob+Smith',
    projectIds: ['1', '2'],
    skills: ['JavaScript', 'TypeScript', 'Backend'],
    availability: 85,
    isActive: true,
    joinedDate: new Date('2024-02-01'),
  },
  {
    id: '3',
    name: 'Carol Williams',
    email: 'carol@example.com',
    role: MemberRole.DEVELOPER,
    avatar: 'https://ui-avatars.com/api/?name=Carol+Williams',
    projectIds: ['1', '3'],
    skills: ['Python', 'SQL', 'Backend'],
    availability: 90,
    isActive: true,
    joinedDate: new Date('2024-03-10'),
  },
  {
    id: '4',
    name: 'David Brown',
    email: 'david@example.com',
    role: MemberRole.QA,
    avatar: 'https://ui-avatars.com/api/?name=David+Brown',
    projectIds: ['1', '4'],
    skills: ['Testing', 'QA', 'Automation'],
    availability: 80,
    isActive: true,
    joinedDate: new Date('2024-04-05'),
  },
  {
    id: '5',
    name: 'Emma Davis',
    email: 'emma@example.com',
    role: MemberRole.DEVELOPER,
    avatar: 'https://ui-avatars.com/api/?name=Emma+Davis',
    projectIds: ['2'],
    skills: ['React', 'Frontend', 'CSS'],
    availability: 75,
    isActive: true,
    joinedDate: new Date('2024-05-12'),
  },
  {
    id: '6',
    name: 'Frank Miller',
    email: 'frank@example.com',
    role: MemberRole.DEVELOPER,
    avatar: 'https://ui-avatars.com/api/?name=Frank+Miller',
    projectIds: ['2'],
    skills: ['React Native', 'Mobile', 'iOS'],
    availability: 70,
    isActive: true,
    joinedDate: new Date('2024-06-01'),
  },
  {
    id: '7',
    name: 'Grace Lee',
    email: 'grace@example.com',
    role: MemberRole.DEVELOPER,
    avatar: 'https://ui-avatars.com/api/?name=Grace+Lee',
    projectIds: ['3'],
    skills: ['DevOps', 'Infrastructure', 'AWS'],
    availability: 95,
    isActive: true,
    joinedDate: new Date('2024-07-15'),
  },
  {
    id: '8',
    name: 'Henry Wilson',
    email: 'henry@example.com',
    role: MemberRole.DEVELOPER,
    avatar: 'https://ui-avatars.com/api/?name=Henry+Wilson',
    projectIds: ['4'],
    skills: ['Data Analysis', 'SQL', 'Analytics'],
    availability: 88,
    isActive: true,
    joinedDate: new Date('2024-08-20'),
  },
];
